---
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: 🐶 Ruff Linter
        language: system
        types: [python]
        entry: poetry run ruff check --fix
        require_serial: true
        stages: [pre-commit, pre-push, manual]
      - id: ruff-format
        name: 🐶 Ruff Formatter
        language: system
        types: [python]
        entry: poetry run ruff format
        require_serial: true
        stages: [pre-commit, pre-push, manual]
      # - id: mypy
      #   name: Static type checking using mypy
      #   language: system
      #   types: [python]
      #   entry: poetry run mypy
      #   require_serial: true
